### ISSUE TITLE
支持Android吗

### ISSUE THREAD

**Issue by changfuguo** [remobile/react-native-refresh-infinite-listview#1]
支持Android吗

**Comment by fov42550564** [comment]
这是纯js编写得，支持ios和android

**Comment by timzaak** [comment]
good job, 谢谢两位！另外，能问下现在在用它做什么app吗？

**Comment by timzaak** [comment]
测试了一下，不支持 android。。
onResponderGrant
onResponderRelease  两个方法无反应

**Comment by fov42550564** [comment]
最近有点忙，有时间我测试一下

**Comment by timzaak** [comment]
嗯，这个是ListView 组件在android上不支持这两个回调，只能等rn-0.16 发版后的用RefreshLayoutAndroid组件,或@changfuguo 的一个解决方案来做。

**Comment by hutuxuhui** [comment]
确实是不支持android,  现在已经rn-0.17了.   @timzaak 是什么解救方案?
